name: Solidity Metrics

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Solidity Metrics
        uses: tintinweb/solidity-metrics-action@v1
        with:
          target: 'src/PasswordStore.sol'
          args: '--output /github/workspace/metrics.md'

      - name: List output files (debug)
        run: ls -lah

      - name: Print metrics (debug)
        run: cat metrics.md || echo "metrics.md not found"

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: solidity-metrics-report
          path: metrics.md
